### ISSUE TITLE
[Bug Report] CompositePanel 样式问题

### ISSUE THREAD

**Issue by nnecec** [alibaba/designable#109]
- [x] I have searched the [issues](https://github.com/alibaba/designable/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce

在 safari 把 source 拖到中间，source 面板会被拖偏移 。 (在 edge 里是好的)

<img width="153" alt="image" src="https://user-images.githubusercontent.com/11435907/137862390-abbab38a-724b-4fae-8bed-2d0dd57060e5.png">

### What is expected?

在 `.dn-resource` 加了个 `overflow: hidden` 可以修复。

**Comment by janryWang** [comment]
fixed
