### ISSUE TITLE
[Bug Report] React version < 17 Failed to execute 'attachShadow' on 'Element': Shadow root cannot be created on a host which already hosts a shadow tree.

### ISSUE THREAD

**Issue by lidianhao123** [alibaba/designable#114]
- [x] I have searched the [issues](https://github.com/alibaba/designable/issues) of this repository and believe that this is not a duplicate.

ref.current is null in react 17 and no null in react 16

[code](https://github.com/alibaba/designable/blob/main/packages/react/src/widgets/IconWidget/index.tsx#L138)
[Potential Issues](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#potential-issues) 

### Steps to reproduce
![image](https://user-images.githubusercontent.com/7970645/138624438-ac82cf18-2d53-4d01-be4e-f81bb48424ef.png)

### What is expected?
no error, run right in React version 16

### Package
@designable/react

**Comment by lidianhao123** [comment]
@janryWang 请问有计划支持 React 16 吗？

**Comment by janryWang** [comment]
> @janryWang 请问有计划支持 React 16 吗？

这个改动还好的吧，可以直接提个PR的
