### ISSUE TITLE
什么时候发布 1.0 班本

### ISSUE THREAD

**Issue by kaoding** [alibaba/designable#126]
如题

**Comment by janryWang** [comment]
应该要年后了，1.0的主要还剩下几件事情
1. 要支持尺寸拖拽
2. 完善文档，案例

年底核心是要把formily2.0正式版发掉

**Comment by wsxe9988** [comment]
啥时尺寸拖拽呢？加标尺的那种吗？

**Comment by kaoding** [comment]
希望在设计区可以固定部分组件（如头和尾），也就是支持表单模板。
@janryWang

**Comment by kaoding** [comment]
> 啥是尺寸拖拽呢？加标尺的那种吗？

尺寸拖拽（我理解）： 就是可以改变组件的width，一行可以放多个组件。
加标尺：应该是在设计的一种设计视图。

**Comment by kaoding** [comment]
到 1.0的时候还有那些事要做，希望可以看到一个工作项列表（to do list），让我们很清楚知道离我们还有多远。

**Comment by janryWang** [comment]
> 希望在设计区可以固定部分组件（如头和尾），也就是支持表单模板。 @janryWang

这个现在就支持，只是你不知道，哈哈，所以需要文档

**Comment by zhaowenjian** [comment]
>厉害了   这是为了做表单的编辑器又造了个轮子么

**Comment by devcui** [comment]
> 应该要年后了，1.0的主要还剩下几件事情
> 
> 1. 要支持尺寸拖拽
> 2. 完善文档，案例
> 3. @desingnable/react 抽离antd
> 
> 年底核心是要把formily2.0正式版发掉

1.designable还有在跟进吗？
2.假如现在开始使用designable的版本，等到发布1.0时会有许多breaking change吗？
3.如果等designable 1.0 的话，大概还需要等多久？

**Comment by janryWang** [comment]
一直在跟进，具体看https://github.com/alibaba/designable/discussions/240
