### ISSUE TITLE
Query error in standalone antd playground

### ISSUE THREAD

**Issue by diegonc** [alibaba/designable#167]
- [x] I have searched the [issues](https://github.com/alibaba/designable/issues) of this repository and believe that this is not a duplicate.

### Reproduction link

This is my attempt at extracting the playground from the `@designable/formily-antd` package into it's own project.

https://github.com/diegonc/designable-playground

### Steps to reproduce

1. Add an input component to the canvas
2. Click configure next to the reactions section of the properties panel
3. Click Ok to close the dialog

https://user-images.githubusercontent.com/261458/146247448-b0675e4d-b68e-4496-8435-331267634ffc.mp4

### What is expected?

The dialog closes without any error on the console.

### What is actually happening?

When the Ok button is clicked the following error is shown on the developer console

    Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at x-reactions (index.js:216)
    at transformer.js:138
    at internals.js:979
    at internals.js:102
    at boundary (internals.js:84)
    at internals.js:102
    at reaction (autorun.js:28)
    at reaction.js:198
    at ArraySet../node_modules/@formily/reactive/esm/array.js.ArraySet.forEachDelete (array.js:44)
    at executePendingReactions (reaction.js:193)

The index.js, line 216 looks like the following:

```
React.createElement(SchemaField.String, { name: "type", default: "any", "x-decorator": "FormItem", "x-component": "TypeView", "x-reactions": function (field) {
  var _a;
  if (isVoidField(field))
    return;
  var property = field
    .query('.property')
    .get('inputValues');
  property[0] = (_a = property[0]) !== null && _a !== void 0 ? _a : 'value';
  field.query('.source').take(function (source) {
```
the variable `property` is undefined, thus the error

NOTE: if before step 3 you delete the initial row of the `Associated Fields` table, the error no longer appears in the console

### Package

The code seems to come from the `@designable/formily-setters` package at the line below

https://github.com/alibaba/designable/blob/b7668b4e9c3b64497977dca926d8b6953c07e712/formily/setters/src/components/ReactionsSetter/index.tsx#L320

NOTE: this error does not happen on the online designer ( https://designable-antd.formilyjs.org/ ), it appears to be some problem during the extraction of the playground but I cannot find what is causing the query to fail.

In my reproduction repository, I installed all the code dependencies (imports) as normal dependencies and all the webpack related (direct and transitive dependencies) packages as devDependencies

Any idea of what could be going on? Thanks!

**Comment by janryWang** [comment]
already fixed, please upgrade to beta.42

**Comment by qia0756** [comment]
Tested on beta.42 and beta.43, the problem still exists.

**Comment by qia0756** [comment]
@janryWang Tested on beta.42 and beta.43, the problem still exists.
