### ISSUE TITLE
Issue in Generating JSON Schema from Array of Options

### ISSUE THREAD

**Issue by aminshahnazari** [alibaba/designable#190]
Hi, 
According to the [JSON Schema documents](https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation), valid items of array should be declared in `Items` property. But in Alibaba Designable, When you are using a component which user can choose multiple item from defined options (Select, Cascader, Checkbox), the items defines in `Enum` instead of `Items`. it cause error in validating data with generated schema. 

Current Schema:
```
"schema": {
    "type": "object",
    "properties": {
      "fzvql0vb8lw": {
        "type": "Array<string | number>",
        "title": "Checkbox Group",
        "x-decorator": "FormItem",
        "x-component": "Checkbox.Group",
        "enum": [
          {
            "label": "Item 1",
            "value": 1
          },
          {
            "label": "Item 2",
            "value": 2
          }
        ],
        "x-validator": [],
        "x-decorator-props": {},
        "x-designable-id": "fzvql0vb8lw",
        "x-index": 0
      }
    },
    "x-designable-id": "3e25ew1amiv"
  }
```

Expected:
```
"schema": {
    "type": "object",
    "properties": {
      "fzvql0vb8lw": {
        "type": "Array",
        "title": "Checkbox Group",
        "x-decorator": "FormItem",
        "x-component": "Checkbox.Group",
        "Items": [
          {
            "label": "Item 1",
            "value": 1
          },
          {
            "label": "Item 2",
            "value": 2
          }
        ],
        "x-validator": [],
        "x-decorator-props": {},
        "x-designable-id": "fzvql0vb8lw",
        "x-index": 0
      }
    },
    "x-designable-id": "3e25ew1amiv"
  }
```

**Comment by janryWang** [comment]
At present, Formily Schema does not completely follow the standard JSON Schema protocol. The main consideration is to be more in line with the UI description habits, so it will not continue to iterate with the JSON Schema protocol version. This Schema is more like a DSL in the form scenario.
