### ISSUE TITLE
异步联动校验咋配置

### ISSUE THREAD

**Issue by zhousufa** [alibaba/designable#195]
当前字段的校验取决于另一个字段和本字段的值的服务端校验结果

**Comment by wangzongxu** [comment]
https://formilyjs.org/zh-CN/guide/advanced/validate#%E5%BC%82%E6%AD%A5%E6%A0%A1%E9%AA%8C

**Comment by zhousufa** [comment]
> https://formilyjs.org/zh-CN/guide/advanced/validate#%E5%BC%82%E6%AD%A5%E6%A0%A1%E9%AA%8C

这个是手写的，在编辑器里我是这样试的，不过也能用
`const state = $observable({
  keyword: "",
})

$props({
  onChange(keyword) {
    state.keyword = keyword
  },
})

$effect(() => {
  if (!state.keyword || !$deps.input) {
    return
  }
  $self.loading = true
  fetch(`//some.domain/getSomething?q=${state.keyword}&other=${$deps.input}`)
    .then((response) => response.json())
    .then(
      ({ data }) => {
        $self.loading = false
        $self.dataSource = data
      },
      () => {
        $self.selfErrors = "xxxxx"
      }
    )
}, [state.keyword, $deps.input])
`
