### ISSUE TITLE
@designable/react的IconWidget组件存在typescript编译错误

### ISSUE THREAD

**Issue by xjchenhao** [alibaba/designable#224]
[源码](https://github.com/alibaba/designable/blob/main/packages/react/src/widgets/IconWidget/index.tsx#L92)中是这样的 👇
![image](https://user-images.githubusercontent.com/5373111/154225411-d2b92da6-f935-4c25-99dc-9b1156faf43f.png)

在构建结果（npm包）使用时，忽略了`?.`的判断，变成了下面这样
![image](https://user-images.githubusercontent.com/5373111/154225601-ff1c4fdd-c118-47d3-b456-3ca0c37b9486.png)

我是在给“左侧组合布局面板”添加自定义的svg图标时发现的这个错误（代码见下图1），浏览器控制台报错（见下图2）
![image](https://user-images.githubusercontent.com/5373111/154226673-40896b7d-87fb-4a4c-92a2-d23fd2f497d9.png)

![image](https://user-images.githubusercontent.com/5373111/154226022-de13c57e-9e5a-46e6-b150-be70252598ea.png)

**Comment by janryWang** [comment]
fixed

**Comment by xjchenhao** [comment]
> fixed

thx
