### ISSUE TITLE
[Bug Report]CompositePanel.Item：JSX元素类型没有任何构造或调用签名

### ISSUE THREAD

**Issue by alphabetabc** [alibaba/designable#244]
- [x] I have searched the [issues](https://github.com/alibaba/designable/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
--

### Steps to reproduce
![image](https://user-images.githubusercontent.com/29876424/156725247-d638599d-b601-4ac2-ab29-df94378ec052.png)

### What is expected?
期望在ts中不报错
### Package
@designable/react

**Comment by janryWang** [comment]
fixed
