### ISSUE TITLE
[Bug Report] Pressing two modifier shortcuts at the same time causes an error

### ISSUE THREAD

**Issue by luruozhou** [alibaba/designable#254]
- [x] I have searched the [issues](https://github.com/alibaba/designable/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://designable-antd.formilyjs.org/

### Steps to reproduce
初次进入页面， 按下组合键 shift+command (注意先按shift，再按command。顺序有先后)。

### What is expected?
不报错
### What is actually happening?
控制台 Shortcut.js 会报错
<img width="547" alt="image" src="https://user-images.githubusercontent.com/10755486/157399718-b828c260-0d9b-4e71-9019-b92262e659fd.png">
<img width="613" alt="image" src="https://user-images.githubusercontent.com/10755486/157399787-06685739-220d-4ae2-8730-4e9b093de568.png">
首先是外层for循环没加this， 第二是整个逻辑判断应该有问题。 应该是 this.codes 中有一项match上则返回true，否则返回false。 而且如果是按下两个 modifer键， 按下的顺序不同会导致 codes里的顺序也不同
### Package
1.0.0-beta.45

**Comment by janryWang** [comment]
fixed
