### ISSUE TITLE
[Bug Report]折叠面板双击左上角编辑标题，直接粘贴内容无法同步到schema

### ISSUE THREAD

**Issue by ace0109** [alibaba/designable#255]
- [x] I have searched the [issues](https://github.com/alibaba/designable/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce

折叠面板双击左上角编辑标题，直接快捷键粘贴内容

### What is expected?

直接粘贴内容需要即使同步到schema

### What is actually happening?

无法同步到schema

### Package

![image](https://user-images.githubusercontent.com/18433582/157584473-64aaf81e-15bd-40d5-bf25-52fed9ad9ce9.png)

**Comment by janryWang** [comment]
fixed
