### ISSUE TITLE
JSX element type 'CompositePanel.Item' does not have any construct or call signatures.

### ISSUE THREAD

**Issue by sauron0914** [alibaba/designable#262]

**Comment by sauron0914** [comment]
> 

![image](https://user-images.githubusercontent.com/25734944/158974744-7f64bad6-7774-4bc2-be08-32327d85780d.png)

**Comment by houzhitaohzt** [comment]
Excuse me, how to solve this problem @sauron0914

**Comment by icex** [comment]
same here.. how do you get this fixed?
