### ISSUE TITLE
配置响应器规则报错

### ISSUE THREAD

**Issue by gehaiyi** [alibaba/designable#267]
https://designable-antd.formilyjs.org/

![image](https://user-images.githubusercontent.com/24401165/160800786-5f10e4a1-26f9-4612-9788-5997f6d51a87.png)

![image](https://user-images.githubusercontent.com/24401165/160800921-9b17f309-5521-478a-9f86-6a37bb0c5971.png)
配置响应器规则时会默认有一个依赖字段，如果不删除，保存规则时就会报错。
如果删除后，保存正常，但是修改响应器规则时还会出现默认的依赖字段，ok后继续报错。

昨天使用正常，今天出现问题。

**Comment by nasawz** [comment]
我这里也是同样的问题

**Comment by janryWang** [comment]
fixed
