### ISSUE TITLE
monaco-editor loader有一个文件不能加载本地的

### ISSUE THREAD

**Issue by huangwentai** [alibaba/designable#278]
- [x] I have searched the [issues](https://github.com/alibaba/designable/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
官方教程
![image](https://user-images.githubusercontent.com/19923827/162422523-228c1804-c9e3-4635-863b-000d2012a743.png)
代码编写
![image](https://user-images.githubusercontent.com/19923827/162422756-0c9d2a38-4bed-4c98-a12d-54a18c5f042d.png)

### What is expected?
正常加载本地的依赖

### What is actually happening?
![image](https://user-images.githubusercontent.com/19923827/162422877-266467d4-a5aa-4b65-ac0b-c0cb8e1a660c.png)
![image](https://user-images.githubusercontent.com/19923827/162423013-e93ca03d-6db2-4f15-a9ee-95380476b68c.png)

### Package
应该是formily编辑器引用的代码初始化在了我的代码前面，没能把我的loader的config加进去，而且试了setNpmCDNRegistry也没改动到这个loader

拜托了

**Comment by huangwentai** [comment]
找到问题所在了，因为import会提前，所以把改配置的方法弄出文件import就按照顺序了

**Comment by weilaiqishi** [comment]
> 找到问题所在了，因为import会提前，所以把改配置的方法弄出文件import就按照顺序了

如何解决的

**Comment by wwyx778** [comment]
> > 找到问题所在了，因为import会提前，所以把改配置的方法弄出文件import就按照顺序了
> 
> 如何解决的

designable 内部这个问题已经修复了，参考
https://github.com/alibaba/designable/commit/65f08411cac17393eb6520191a035adcd52ef0a9

**Comment by weilaiqishi** [comment]
啥时候发版到npm。。。
