### ISSUE TITLE
属性配置面板部分属性在中文模式下显示英文

### ISSUE THREAD

**Issue by wsxe9988** [alibaba/designable#44]
- [x] I have searched the [issues](https://github.com/alibaba/designable/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://designable-antd.formilyjs.org/
### Steps to reproduce
![lALPD3Irvs5S3BbNA6PNB3w_1916_931](https://user-images.githubusercontent.com/5828057/130311852-7026aea3-70bc-4f30-af58-64db041482c7.png)
![lALPD4PvOAYwVL7NA6PNB38_1919_931](https://user-images.githubusercontent.com/5828057/130311872-e516f7e6-0aa1-4748-92df-5bc353291f8b.png)

### What is expected?
期待属性配置面板相关label内容以及tooltip内容在中文模式下显示中文，在英文模式下显示英文，正确的国际化

**Comment by janryWang** [comment]
这个问题是这些属性我不知道中文应该咋描述

**Comment by wsxe9988** [comment]
中文应该怎么描述，我可以找下，回复在该issure,你看合不合适

**Comment by wsxe9988** [comment]
确实不好描述，就英文吧
