### ISSUE TITLE
[Bug Report]安装@designable/react 报错

### ISSUE THREAD

**Issue by eJayYoung** [alibaba/designable#57]
- [x] I have searched the [issues](https://github.com/alibaba/designable/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
安装@designable/react 报错，找不到@formily/react"模块

原因：[NodePathWidget 引用了@formily/react](https://github.com/alibaba/designable/blob/main/packages/react/src/widgets/NodePathWidget/index.tsx#L6)，但是[@designable/react的package.json没有安装@formily/react](https://github.com/alibaba/designable/blob/main/packages/react/package.json)

### What is expected?
安装后可以正常运行

### What is actually happening?
安装@designable/react 报错，找不到@formily/react"模块

shell提示
```bash
> ../../node_modules/@designable/react/esm/widgets/NodePathWidget/index.js:6:25: error: Could not resolve "@formily/react" (mark it as external to exclude it from the bundle)
    6 │ import { observer } from '@formily/react';
      ╵                          ~~~~~~~~~~~~~~~~
```

### Package
@designable/react 0.5.27

**Comment by eJayYoung** [comment]
安装完@formily/react，又提示了`Internal server error: '~antd/lib/style/themes/default.less' wasn't found`，然而安装了antd后，并没有解决

**Comment by janryWang** [comment]
已修复
