### ISSUE TITLE
[Bug Report] 表单设计器-DateRangePicker-选择器类型为季度时显示内容错误

### ISSUE THREAD

**Issue by wsxe9988** [alibaba/designable#75]
- [x] I have searched the [issues](https://github.com/alibaba/designable/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://designable-antd.formilyjs.org/
### Steps to reproduce
1.将DateRangePicker组件拖到画布里
2.组件属性-选择器类型选择为季度
![4161B435-5BAC-407b-9A72-BA19F0A79D30](https://user-images.githubusercontent.com/5828057/134202540-a9383f62-04df-4652-8bf0-2ac56c38fe50.png)
3.预览
![image](https://user-images.githubusercontent.com/5828057/134202615-7b4c7e3a-d24d-4f8a-a91b-5845a2d0fa53.png)

### What is expected?
期望预览时点击日期选择框，呈现的是季度
### What is actually happening?
目前预览时点击日期选择框，呈现的是年份
### Package
designable- v1.0.0-beta.4

**Comment by janryWang** [comment]
已修复
