### ISSUE TITLE
Config style is not working when second time config

### ISSUE THREAD

**Issue by RihuaChen** [alibaba/designable#78]
- [x] I have searched the [issues](https://github.com/alibaba/designable/issues) of this repository and believe that this is not a duplicate.

### Reproduction Step

Config style is not working

### Steps to reproduce
![image](https://user-images.githubusercontent.com/11918443/134895017-657d3411-36e7-4eb1-9440-b1a12d89c248.png)

### What is expected?
Config style working right way

### What is actually happening?
Color picker was freeze when pick the second time

### Package
1.0.0.-beta.11

**Comment by janryWang** [comment]
修复
