### ISSUE TITLE
配置了组件自定义style的props，style修改之后不会触发样式的改变

### ISSUE THREAD

**Issue by kaketsu** [alibaba/designable#79]
- [x] I have searched the [issues](https://github.com/alibaba/designable/issues) of this repository and believe that this is not a duplicate.

### Bug
![image](https://user-images.githubusercontent.com/10204163/134898343-d2e5bffd-2eb1-4493-9327-ccc709448692.png)

![image](https://user-images.githubusercontent.com/10204163/134898426-b827ff11-a471-4c51-a464-6d39372d9c1d.png)

如上图，配置了自定义style的props，但是整个style修改之后不会触发样式的改变。

### What is expected?
正常改变组件的样式

### What is actually happening?
可能是style proxy 坏了

**Comment by janryWang** [comment]
请给issue加上标题

**Comment by janryWang** [comment]
修复
