### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Lewis-li-0** [alibaba/designable#80]
- [x] I have searched the [issues](https://github.com/alibaba/designable/issues) of this repository and believe that this is not a duplicate.
![image](https://user-images.githubusercontent.com/24446460/134928734-7ea242e7-5d79-4b4d-91ec-983ce386a8c4.png)

### Steps to reproduce
推拽输入框后，鼠标点击组件样式的宽度输入框加减按钮，无效
### What is expected?
宽度正常增加或减少
### What is actually happening?
未知

**Comment by janryWang** [comment]
请给issue加上标题

**Comment by janryWang** [comment]
修复
